addSbtPlugin("io.get-coursier" % "sbt-coursier" % "2.0.11-1")
addSbtPlugin("org.scalameta" % "sbt-mdoc" % "2.3.3")
addSbtPlugin("org.xerial.sbt" % "sbt-sonatype" % "3.9.13")
addSbtPlugin("com.jsuereth" % "sbt-pgp" % "2.0.0")
addSbtPlugin("io.github.nafg.mergify" % "sbt-mergify-github-actions" % "0.5.0")
